mujoco_config:
  model: "/home/saitama/Documents/panda_robot_learning/franka_emika_panda/mjx_single_cube.xml"


ik_config:
  max_iters: 50
  tol_pos: 0.001    # 1e-3
  tol_ori: 0.01     # 1e-2
  damp: 0.01        # 1e-2
  ori_weight: 0.2

robot_config:
  ee_body: "hand"
  base_body: "link0"
  grip_joint: "finger_joint1"
  num_dof: 7  # number of arm DOFs (no gripper)